{{- if .Values.global.healthService.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.global.healthService.name }}-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: {{ .Values.global.healthService.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.global.healthService.name }}
{{- end }}
