apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.aiService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.global.aiService.name }}
  ports:
    - port: {{ .Values.global.aiService.port }}
      targetPort: {{ .Values.global.aiService.port }}
