{{- if and .Values.global.gateway.enabled (eq .Release.Name "meditrack-dev") }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: meditrack-envoy-config
  namespace: {{ .Values.global.namespace.infra }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
      envoyDeployment:
        replicas: 2
        container:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
{{- end }}
