{{- if .Values.global.gateway.enabled }}
{{- $isdev := eq .Release.Name "meditrack-dev" }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-protected-routes
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Release.Name }}-gateway
      namespace: {{ .Values.global.namespace.infra }}
      sectionName: {{ .Values.global.gateway.listenerName }}
    - name: {{ .Release.Name }}-gateway
      namespace: {{ .Values.global.namespace.infra }}
      sectionName: {{ .Values.global.gateway.listenerName }}-https
  hostnames:
    - {{ if $isdev }}{{ .Values.global.gateway.hosts.dev }}{{ else }}{{ .Values.global.gateway.hosts.prod }}{{ end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/auth/me
        - path:
            type: PathPrefix
            value: /api/auth/logout
      backendRefs:
        - name: {{ .Values.global.userService.name }}
          port: {{ .Values.global.userService.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /api/medications
      backendRefs:
        - name: {{ .Values.global.medicalService.name }}
          port: {{ .Values.global.medicalService.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /api/symptoms
      backendRefs:
        - name: {{ .Values.global.healthService.name }}
          port: {{ .Values.global.healthService.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /api/visits
      backendRefs:
        - name: {{ .Values.global.healthService.name }}
          port: {{ .Values.global.healthService.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /api/ai
      backendRefs:
        - name: {{ .Values.global.aiService.name }}
          port: {{ .Values.global.aiService.port }}
{{- end }}
