{{- if .Values.global.gateway.enabled }}
{{- $isdev := eq .Release.Name "meditrack-dev" }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: meditrack-jwt-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ .Release.Name }}-protected-routes
  jwt:
    providers:
      - name: meditrack-provider
        issuer: {{ .Values.global.gateway.jwt.issuer }}
        audiences:
          - {{ .Values.global.gateway.jwt.audience }}
        remoteJWKS:
          uri: http://{{ .Values.global.userService.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.userService.port }}/api/auth/jwks
        claimToHeaders:
          - claim: sub
            header: X-User-ID
          - claim: email
            header: X-User-Email
{{- end }}
