apiVersion: v1
kind: LimitRange
metadata:
  name: meditrack-limits
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.global.limitRange.default.cpu }}
        memory: {{ .Values.global.limitRange.default.memory }}
      defaultRequest:
        cpu: {{ .Values.global.limitRange.defaultRequest.cpu }}
        memory: {{ .Values.global.limitRange.defaultRequest.memory }}
      max:
        cpu: {{ .Values.global.limitRange.max.cpu }}
        memory: {{ .Values.global.limitRange.max.memory }}
      min:
        cpu: {{ .Values.global.limitRange.min.cpu }}
        memory: {{ .Values.global.limitRange.min.memory }}
