apiVersion: v1
kind: ConfigMap
metadata:
  name: meditrack-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.global.config.environment | quote }}
  LOG_LEVEL: {{ .Values.global.config.logLevel | quote }}
  REDIS_URL: {{ .Values.global.config.redisUrl | quote }}
  MEDICAL_SERVICE_URL: {{ .Values.global.config.medicalServiceUrl | quote }}
  HEALTH_SERVICE_URL: {{ .Values.global.config.healthServiceUrl | quote }}
  USER_SERVICE_URL: {{ .Values.global.config.userServiceUrl | quote }}
  ALLOWED_ORIGINS: {{ .Values.global.config.allowedOrigins | quote }}
